### ISSUE TITLE
Threshold "high-drift" introduced in v2.6.0 cannot be properly parsed as label in Prometheus config, due to the use of hyphen ("-")

### ISSUE THREAD

**Issue by stamatis-maritsas-sympower** [sapcc/ntp_exporter#112]
Hi there,

I believe I have bumped into an issue and wanted to share with you and understand what are the options here.

Some data first:

- Have been a user of v2.5.0 without any issues so far.
- Using Variable NTP server (mode 2) when running the NTP exporter as a service.
- How my Prometheus config for the NTP job looks like:

```yaml
- job_name: 'NTP_internal'
    scrape_interval: 30s
    metrics_path: /metrics 
    static_configs:
    - targets: [ 'ntp1.sympower.net', 'ntp2.sympower.net' ]
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__address__]
      target_label: Name
    - source_labels: [__address__]
      target_label: __param_protocol
      replacement: '4'
    - source_labels: [__address__]
      target_label: __param_duration
      replacement: '10s'
    - source_labels: [__address__]
      target_label: Environment
      replacement: 'catdoor'
    - source_labels: [__address__]
      target_label: Component
      replacement: 'ntp-server'
    - source_labels: [__address__]
      target_label: Product
      replacement: 'infra'
    - source_labels: [__address__]
      target_label: Country
      replacement: 'eu'
    - source_labels: [__address__]
      target_label: Location
      replacement: 'eu'
    - target_label: __address__
      replacement: {{ ntp_exporter_address | default ('localhost:9559') }}	
```

#### Problem

- After upgrading ntp_exporter to v2.6.1 my endpoints have been reported as DOWN in Prometheus target scope:

![Screenshot 2024-07-31 at 11 22 28](https://github.com/user-attachments/assets/6d566259-4fbd-4621-9dac-2890305b216e)

We have identified an issue with the new threshold introduced in v2.6.0 (called `"high-drift"`) that is now included in the HTTP request for the metrics. 

Prometheus labelling name standard, though, does not allow to use `-` (hyphens) and this is why when we restarted Prometheus the label `"high-drift"` did not detected having as outcome the endpoints to be down without collecting any logs. We have tried a lot of different things to get the `high-drift` label remapped in Prometheus configuration (i.e. by using `relabel_configs:`) but without any success.

#### Questions

1. Is there a possibility to maybe include an option to interpret `high-drift` also as `high_drift` if needed in cases like ours?
2. Is there is already a workaround for this that you are aware or you have any other suggestion, I am more than happy to hear it.
